export enum MENU_ROUTER_ENUM {
  "PERSON_REGISTRATION_FORM" = "/person/person",
  "GROUP_REGISTRATION_FORM" = "/person/group",
  "OTHER_SETTING" = "/sale/setting/othersetting",
  "PRE_INVOICE_FORM" = "/sale/pre-invoice",
  "LOADING_PERMISSION" = "/sale/loading-permission",
  "ISSUE_EXIST_DOCUMENT" = "/sale/exit-permission-issue",
  "CREAT_ORDER_FORM" = "/sale/order",
  "ORDER_SHIPPING_STATUS" = "/sale/order/shipping-status",
  "CONFIRM_PRE_INVOICE_FORM" = "/sale/preinvoice-confirm",
  "CONFIRM_MANAGER_PRE_INVOICE_FORM" = "/sale/preinvoice-confirm-manager",
  "CONFIRM_CUSTOMER_PRE_INVOICE_FORM" = "/sale/preinvoice-confirm-customer",
  "DEFINITION_SERVICE_AND_GOODS_FORM" = "/warehouse/action/goods-and-service",
  "DEFINITION_GOODS_GROUPING_FORM" = "/warehouse/action/goodsGroup",
  "DEFINITION_MEASUREMENT_UNIT_FORM" = "/warehouse/action/measurementUnit",
  "DEFINITION_KOP_STONE_TITLE_FORM" = "/warehouse/action/kopStoneTitle",
  "DEFINITION_KOP_AND_STONE_DEGREE_FORM" = "/warehouse/action/kopStoneDegree",
  "DEFINITION_STONE_FINISHING_FORM" = "/warehouse/action/finishing",
  "DEFINITION_WAREHOUSE_WAREHOUSE_CATEGORY_FORM" = "/warehouse/action/warehouse-and-category",
}
