export enum WORK_ORDER_TAB {
  WORK_ORDER = "RETURN_INVOICE_FORM",
  WORK_LOG = "RETURN_INVOICE_FORM_LIST",
}
export enum TabType {
  WORK_ORDER = "WORK_ORDER",
  WORK_LOG = "WORK_LOG",
}

export enum WORK_ORDER_DATA_ENTRY_TYPES {
  GET_WORK_ORDER_BY_CODE = "GET_WORK_ORDER_BY_CODE",
  CREATE_WORK_ORDER_FROM_WORK_REQUEST = "CREATE_WORK_ORDER_FROM_WORK_REQUEST",
}
